import './globals.css';
import StoreProvider from './Context/Context';
import { Suspense } from 'react';
import Loading from './Loading';
import toast, { Toaster } from 'react-hot-toast';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Prediction Farming Application',
  description: 'Generated by Group 12',
  viewport: 'width=device-width, initial-scale=1, maximum-scale=1',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <StoreProvider>
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        </StoreProvider>
      </body>
    </html >
  )
}
