import './globals.css';
import StoreProvider from './Context/Context';
import toast, { Toaster } from 'react-hot-toast';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Prediction Farming Application',
  description: 'Generated by Group 12',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
