import StoreProvider from '../Context/Context';
import toast, { Toaster } from 'react-hot-toast';
import { Inter } from 'next/font/google'
import { Header, SideBar } from '../components';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Prediction Farming Application',
    description: 'Generated by Group 12',
    viewport: 'width=device-width, initial-scale=1, maximum-scale=1', 
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Toaster />
                <StoreProvider>
                    <div className='flex flex-row w-full min-h-full h-full'>
                         <SideBar />
                        <div className='flex flex-col w-full min-h-full bg-white overflow-x-hidden'>
                            <Header />
                            {children}
                        </div>
                    </div>
                </StoreProvider>
            </body>
        </html>
    )
}
